// Code generated by goyacc -o parser.go parser.go.y. DO NOT EDIT.

//line parser.go.y:2
package parser

import __yyfmt__ "fmt"

//line parser.go.y:2

import (
	"path/filepath"
)

//line parser.go.y:40
type yySymType struct {
	yys   int
	token Token
	expr  *Node
	atom  Atom
}

const TAssert = 57346
const TBreak = 57347
const TCase = 57348
const TContinue = 57349
const TElse = 57350
const TFor = 57351
const TFunc = 57352
const TIf = 57353
const TLen = 57354
const TNot = 57355
const TReturn = 57356
const TReturnNil = 57357
const TUse = 57358
const TSwitch = 57359
const TTypeof = 57360
const TVar = 57361
const TYield = 57362
const TYieldNil = 57363
const TAddAdd = 57364
const TSubSub = 57365
const TEqeq = 57366
const TNeq = 57367
const TLsh = 57368
const TRsh = 57369
const TURsh = 57370
const TLte = 57371
const TGte = 57372
const TIdent = 57373
const TNumber = 57374
const TString = 57375
const TAddEq = 57376
const TSubEq = 57377
const TMulEq = 57378
const TDivEq = 57379
const TModEq = 57380
const TAndEq = 57381
const TOrEq = 57382
const TXorEq = 57383
const TLshEq = 57384
const TRshEq = 57385
const TURshEq = 57386
const TSquare = 57387
const ASSIGN = 57388
const FUN = 57389
const TOr = 57390
const TAnd = 57391
const UNARY = 57392
const TMinMin = 57393

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"TAssert",
	"TBreak",
	"TCase",
	"TContinue",
	"TElse",
	"TFor",
	"TFunc",
	"TIf",
	"TLen",
	"TNot",
	"TReturn",
	"TReturnNil",
	"TUse",
	"TSwitch",
	"TTypeof",
	"TVar",
	"TYield",
	"TYieldNil",
	"TAddAdd",
	"TSubSub",
	"TEqeq",
	"TNeq",
	"TLsh",
	"TRsh",
	"TURsh",
	"TLte",
	"TGte",
	"TIdent",
	"TNumber",
	"TString",
	"'{'",
	"'['",
	"'('",
	"TAddEq",
	"TSubEq",
	"TMulEq",
	"TDivEq",
	"TModEq",
	"TAndEq",
	"TOrEq",
	"TXorEq",
	"TLshEq",
	"TRshEq",
	"TURshEq",
	"TSquare",
	"'T'",
	"ASSIGN",
	"FUN",
	"TOr",
	"TAnd",
	"'>'",
	"'<'",
	"'+'",
	"'-'",
	"'|'",
	"'^'",
	"'*'",
	"'/'",
	"'%'",
	"'&'",
	"UNARY",
	"'~'",
	"'#'",
	"TMinMin",
	"'}'",
	"'='",
	"']'",
	"'.'",
	"';'",
	"','",
	"':'",
	"')'",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.go.y:385

func expandSwitch(switchTok Token, sub *Node, cases []*Node) *Node {
	subject := ANodeS("switch_tmp_var")
	ret := ChainNode(CompNode("set", subject, sub).setPos0(switchTok))

	var lastif, root *Node
	var defaultCase *Node

	for i := 0; i < len(cases); i += 2 {
		if cases[i].A() == "else" {
			defaultCase = cases[i+1]
			continue
		}

		casestat := CompNode("if", CompNode("==", subject, cases[i]), cases[i+1]).setPos0(cases[i])
		if lastif != nil {
			lastif.Cappend(ChainNode(casestat))
		} else {
			root = casestat
		}
		lastif = casestat
	}

	if defaultCase == nil {
		lastif.Cappend(CompNode(AChain))
	} else {
		if root == nil {
			ret.Cappend(defaultCase)
			return ret
		}

		lastif.Cappend(defaultCase)
	}

	ret.Cappend(root)
	return ret
}

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 1377

var yyAct = [...]int{

	197, 112, 169, 69, 195, 68, 115, 191, 32, 192,
	1, 146, 50, 51, 228, 220, 170, 39, 176, 25,
	169, 175, 54, 57, 58, 40, 64, 26, 174, 114,
	67, 53, 103, 60, 63, 115, 104, 105, 193, 20,
	114, 119, 204, 106, 107, 108, 109, 52, 111, 120,
	172, 139, 49, 110, 27, 59, 132, 131, 144, 6,
	123, 137, 182, 184, 142, 143, 47, 145, 24, 61,
	148, 25, 25, 113, 127, 25, 3, 117, 38, 26,
	26, 37, 130, 26, 17, 149, 150, 151, 152, 153,
	154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
	164, 165, 166, 167, 203, 141, 27, 27, 136, 62,
	27, 6, 30, 129, 171, 16, 173, 65, 134, 128,
	24, 15, 98, 99, 100, 178, 179, 126, 3, 5,
	4, 18, 183, 19, 181, 118, 17, 2, 0, 188,
	0, 0, 66, 190, 0, 189, 0, 0, 0, 0,
	0, 0, 0, 0, 25, 0, 94, 95, 96, 102,
	0, 0, 26, 0, 0, 0, 0, 16, 0, 168,
	0, 194, 0, 15, 0, 0, 196, 0, 198, 0,
	0, 5, 0, 0, 0, 205, 0, 0, 209, 27,
	208, 212, 207, 0, 0, 0, 0, 185, 25, 0,
	25, 0, 216, 0, 0, 217, 26, 0, 26, 221,
	0, 0, 0, 0, 223, 0, 0, 25, 25, 0,
	0, 0, 0, 0, 0, 26, 26, 231, 0, 0,
	229, 230, 25, 27, 25, 27, 0, 0, 232, 233,
	26, 200, 26, 202, 0, 0, 0, 25, 25, 25,
	25, 25, 27, 27, 0, 26, 26, 26, 26, 26,
	214, 215, 0, 0, 0, 0, 0, 27, 0, 27,
	0, 0, 0, 0, 0, 224, 0, 225, 0, 0,
	0, 0, 27, 27, 27, 27, 27, 6, 6, 0,
	6, 6, 234, 0, 0, 0, 24, 24, 0, 24,
	24, 0, 0, 0, 3, 3, 0, 3, 3, 71,
	72, 0, 17, 17, 0, 17, 17, 0, 0, 0,
	0, 0, 0, 0, 73, 74, 75, 76, 77, 78,
	79, 80, 81, 82, 83, 70, 0, 0, 0, 0,
	0, 0, 0, 16, 16, 0, 16, 16, 0, 15,
	15, 0, 15, 15, 0, 0, 133, 5, 5, 0,
	5, 5, 11, 9, 0, 10, 0, 21, 0, 22,
	0, 0, 12, 13, 14, 23, 0, 0, 7, 8,
	0, 0, 90, 91, 98, 99, 100, 89, 88, 31,
	0, 0, 20, 0, 29, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	84, 85, 86, 87, 92, 93, 101, 97, 94, 95,
	96, 102, 11, 9, 0, 10, 0, 21, 0, 22,
	124, 125, 12, 13, 14, 23, 0, 0, 7, 8,
	0, 0, 90, 91, 98, 99, 100, 89, 88, 31,
	0, 0, 20, 0, 29, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	84, 85, 86, 87, 92, 93, 101, 97, 94, 95,
	96, 102, 11, 9, 0, 10, 0, 21, 0, 22,
	0, 226, 12, 13, 14, 23, 0, 0, 7, 8,
	0, 0, 90, 91, 98, 99, 100, 89, 88, 31,
	0, 0, 20, 0, 29, 90, 91, 98, 99, 100,
	89, 88, 0, 0, 0, 0, 0, 0, 0, 0,
	84, 85, 86, 87, 92, 93, 101, 97, 94, 95,
	96, 102, 0, 84, 85, 86, 87, 92, 93, 101,
	97, 94, 95, 96, 102, 98, 99, 100, 71, 72,
	0, 186, 0, 0, 0, 187, 90, 91, 98, 99,
	100, 89, 88, 73, 74, 75, 76, 77, 78, 79,
	80, 81, 82, 83, 70, 92, 93, 101, 97, 94,
	95, 96, 102, 0, 84, 85, 86, 87, 92, 93,
	101, 97, 94, 95, 96, 102, 90, 91, 98, 99,
	100, 89, 88, 0, 0, 0, 0, 147, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 90, 91, 98,
	99, 100, 89, 88, 84, 85, 86, 87, 92, 93,
	101, 97, 94, 95, 96, 102, 90, 91, 98, 99,
	100, 89, 88, 0, 0, 0, 227, 86, 87, 92,
	93, 101, 97, 94, 95, 96, 102, 0, 0, 0,
	0, 0, 0, 0, 84, 85, 86, 87, 92, 93,
	101, 97, 94, 95, 96, 102, 90, 91, 98, 99,
	100, 89, 88, 0, 0, 0, 219, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 84, 85, 86, 87, 92, 93,
	101, 97, 94, 95, 96, 102, 90, 91, 98, 99,
	100, 89, 88, 0, 0, 0, 213, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 84, 85, 86, 87, 92, 93,
	101, 97, 94, 95, 96, 102, 90, 91, 98, 99,
	100, 89, 88, 0, 0, 0, 177, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 90, 91, 98,
	99, 100, 89, 88, 84, 85, 86, 87, 92, 93,
	101, 97, 94, 95, 96, 102, 90, 91, 98, 99,
	100, 89, 88, 0, 0, 201, 85, 86, 87, 92,
	93, 101, 97, 94, 95, 96, 102, 90, 91, 98,
	99, 100, 89, 88, 84, 85, 86, 87, 92, 93,
	101, 97, 94, 95, 96, 102, 0, 0, 0, 0,
	0, 0, 0, 0, 199, 84, 85, 86, 87, 92,
	93, 101, 97, 94, 95, 96, 102, 90, 91, 98,
	99, 100, 89, 88, 0, 180, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 90, 91, 98, 99,
	100, 89, 88, 0, 0, 84, 85, 86, 87, 92,
	93, 101, 97, 94, 95, 96, 102, 0, 0, 0,
	0, 0, 0, 222, 84, 85, 86, 87, 92, 93,
	101, 97, 94, 95, 96, 102, 0, 28, 0, 36,
	44, 0, 211, 34, 28, 35, 36, 44, 0, 0,
	34, 0, 35, 0, 0, 0, 0, 0, 31, 33,
	41, 48, 0, 29, 0, 31, 33, 41, 48, 0,
	29, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 42, 0, 0, 0, 0, 0,
	46, 42, 43, 45, 0, 0, 0, 46, 0, 43,
	45, 28, 140, 36, 44, 0, 0, 34, 138, 35,
	0, 28, 0, 36, 44, 0, 0, 34, 0, 35,
	0, 0, 56, 33, 41, 48, 0, 29, 0, 0,
	0, 0, 31, 33, 41, 48, 0, 29, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 42, 0,
	0, 0, 0, 0, 46, 0, 43, 45, 42, 0,
	0, 0, 0, 55, 46, 0, 43, 45, 0, 11,
	9, 210, 10, 0, 21, 28, 22, 0, 0, 12,
	13, 14, 23, 0, 0, 7, 8, 90, 91, 98,
	99, 100, 89, 88, 0, 0, 31, 135, 0, 20,
	0, 29, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 84, 85, 86, 87, 92,
	93, 101, 97, 94, 95, 96, 102, 0, 0, 0,
	0, 0, 0, 122, 90, 91, 98, 99, 100, 89,
	88, 0, 0, 121, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 28, 0, 36, 44, 0, 0, 34,
	0, 35, 84, 85, 86, 87, 92, 93, 101, 97,
	94, 95, 96, 102, 31, 33, 41, 48, 0, 29,
	0, 0, 0, 0, 90, 91, 98, 99, 100, 89,
	88, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	42, 0, 0, 0, 0, 0, 46, 0, 43, 45,
	0, 116, 84, 85, 86, 87, 92, 93, 101, 97,
	94, 95, 96, 102, 218, 0, 28, 0, 36, 44,
	0, 206, 34, 28, 35, 36, 44, 0, 0, 34,
	0, 35, 0, 0, 0, 0, 0, 31, 33, 41,
	48, 0, 29, 0, 31, 33, 41, 48, 0, 29,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 28,
	0, 36, 44, 42, 0, 34, 0, 35, 0, 46,
	42, 43, 45, 71, 72, 0, 46, 0, 43, 45,
	31, 33, 41, 48, 0, 29, 0, 0, 73, 74,
	75, 76, 77, 78, 79, 80, 81, 82, 83, 0,
	0, 0, 0, 0, 0, 0, 42, 0, 0, 0,
	0, 0, 46, 0, 43, 45, 11, 9, 0, 10,
	0, 21, 28, 22, 0, 0, 12, 13, 14, 23,
	0, 0, 7, 8, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 31, 11, 9, 20, 10, 29, 21,
	0, 22, 0, 0, 12, 13, 14, 23, 0, 0,
	7, 8, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 31, 0, 0, 20, 0, 29,
}
var yyPact = [...]int{

	-1000, 1312, -1000, -1000, -1000, -1000, -1000, 1249, -1000, -1000,
	-1000, 1249, 1249, -1000, 14, -1000, -1000, -1000, -1000, -1000,
	-1000, 981, 1249, 1249, 24, -2, -1000, -43, -1000, 1249,
	-1000, 536, 1150, -1000, -1, 1249, 1249, -1000, -1000, -2,
	-1000, -1000, 1249, 1249, 1249, 1249, 22, 4, 1133, -1000,
	1100, 1150, -1000, 1055, 358, 1249, 287, 478, 1053, -7,
	924, 20, -1000, 917, 1249, 48, -64, 542, -1000, 1249,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 1249, 1249, 1249, 1249, 1249, 1249,
	1249, 1249, 1249, 1249, 1249, 1249, 1249, 1249, 1249, 1249,
	1249, 1249, 1249, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 5, -53, 1249, -25, -1000, -1000, -40, -52, -55,
	702, -1000, -1000, -1000, 1249, 1249, -1000, -1000, -1000, -1000,
	-1000, -1000, 803, 1249, 54, 57, 1340, 491, 1249, 1251,
	-1000, -66, 1150, 1150, -1000, -1000, -1000, -1000, 1150, 763,
	603, 529, 529, 529, 529, 529, 529, 96, 96, -1000,
	-1000, -1000, 96, -1000, -1000, -1000, 96, -1000, -1000, 7,
	1249, 1150, -1000, -71, -1000, 1249, 1249, 1249, 782, 1150,
	1340, 742, 1340, 36, 1213, -1000, 1251, 991, 862, -1000,
	1249, 1249, -1000, -1000, 1150, -1000, 662, 1150, 1150, 1340,
	1340, 1249, -1000, -1000, 1206, 622, -59, -1000, 1249, 843,
	-1000, -1000, 1150, 1249, 1340, -1000, 418, 582, -60, -1000,
	-1000, 1150, -1000, 1150, -1000, -1000, 1249, -1000, -1000, 1312,
	1312, 478, 1312, 1312, -1000,
}
var yyPgo = [...]int{

	0, 10, 57, 137, 52, 1, 41, 135, 0, 25,
	5, 3, 17, 133, 127, 119, 113, 82, 132, 60,
	74, 131, 130, 66, 117, 112, 109, 81, 48, 78,
	77,
}
var yyR1 = [...]int{

	0, 1, 1, 2, 14, 3, 3, 3, 3, 19,
	19, 19, 19, 19, 19, 22, 22, 22, 22, 13,
	13, 13, 10, 10, 11, 11, 11, 11, 11, 11,
	11, 11, 11, 11, 11, 9, 9, 9, 9, 9,
	9, 15, 15, 15, 15, 15, 15, 16, 16, 17,
	18, 18, 18, 18, 24, 24, 24, 23, 21, 20,
	20, 20, 20, 20, 20, 20, 20, 20, 4, 4,
	4, 4, 4, 4, 4, 5, 5, 6, 6, 7,
	7, 8, 8, 8, 8, 8, 8, 8, 8, 8,
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
	8, 8, 8, 8, 12, 12, 12, 12, 25, 26,
	26, 27, 27, 27, 28, 28, 29, 29, 30, 30,
	30, 30,
}
var yyR2 = [...]int{

	0, 0, 2, 3, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 3, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 2, 3, 5, 4, 6,
	5, 3, 6, 7, 7, 9, 4, 3, 5, 5,
	4, 4, 5, 5, 0, 2, 2, 2, 4, 2,
	1, 1, 1, 2, 3, 2, 1, 2, 1, 2,
	4, 6, 5, 5, 3, 1, 3, 1, 3, 3,
	5, 1, 2, 2, 2, 1, 1, 1, 1, 1,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 2,
	2, 2, 2, 2, 1, 3, 1, 3, 2, 2,
	3, 3, 4, 3, 2, 3, 2, 3, 1, 2,
	1, 2,
}
var yyChk = [...]int{

	-1000, -1, -3, -20, -22, -14, -2, 20, 21, 5,
	7, 4, 14, 15, 16, -15, -16, -17, -21, -13,
	34, 9, 11, 17, -23, -12, -9, -4, 10, 36,
	-25, 31, -8, 32, 16, 18, 12, -27, -29, -12,
	-9, 33, 57, 65, 13, 66, 63, -23, 34, -4,
	-8, -8, 33, -1, -8, 72, 31, -8, -8, 31,
	35, 71, -26, 36, 69, -24, -25, -8, -10, -11,
	48, 22, 23, 37, 38, 39, 40, 41, 42, 43,
	44, 45, 46, 47, 52, 53, 54, 55, 30, 29,
	24, 25, 56, 57, 60, 61, 62, 59, 26, 27,
	28, 58, 63, 33, -8, -8, -8, -8, -8, -8,
	31, -28, -5, 69, 36, 31, 68, -30, -7, -6,
	-8, 33, 68, -19, 72, 73, -14, -20, -15, -16,
	-17, -2, -8, 69, -19, 34, -28, -8, 74, 31,
	75, -6, -8, -8, 10, 19, 75, 75, -8, -8,
	-8, -8, -8, -8, -8, -8, -8, -8, -8, -8,
	-8, -8, -8, -8, -8, -8, -8, -8, -2, 73,
	69, -8, 75, -5, 68, 73, 73, 74, -8, -8,
	72, -8, 8, -18, 6, -19, 70, 74, -8, -10,
	-11, 73, 75, 31, -8, 75, -8, -8, -8, 72,
	-19, 73, -19, 68, 6, -8, 8, -10, -11, -8,
	70, 70, -8, 74, -19, -19, -8, -8, 8, 74,
	74, -8, 70, -8, -19, -19, 73, 74, 74, -1,
	-1, -8, -1, -1, -19,
}
var yyDef = [...]int{

	1, -2, 2, 5, 6, 7, 8, 0, 60, 61,
	62, 0, 0, 66, 0, 15, 16, 17, 18, 4,
	1, 0, 0, 0, 0, 19, 20, 114, 54, 0,
	116, 68, 59, 81, 0, 0, 0, 85, 86, 87,
	88, 89, 0, 0, 0, 0, 0, 0, 0, 114,
	63, 65, 67, 0, 0, 0, 68, 0, 0, 0,
	0, 0, 118, 0, 0, 57, 116, 0, 35, 0,
	69, 22, 23, 24, 25, 26, 27, 28, 29, 30,
	31, 32, 33, 34, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 82, 83, 84, 109, 110, 111, 112,
	113, 0, 0, 0, 0, 75, 126, 0, 128, 130,
	77, 64, 3, 41, 0, 0, 9, 10, 11, 12,
	13, 14, 0, 0, 47, 0, 0, 0, 0, 74,
	119, 0, 77, 21, 55, 56, 115, 117, 36, 90,
	91, 92, 93, 94, 95, 96, 97, 98, 99, 100,
	101, 102, 103, 104, 105, 106, 107, 108, 121, 0,
	0, 123, 124, 0, 127, 129, 131, 0, 0, 46,
	0, 0, 0, 0, 0, 58, 70, 0, 0, 38,
	0, 0, 120, 76, 122, 125, 0, 78, 79, 0,
	0, 0, 48, 49, 0, 0, 0, 37, 0, 0,
	72, 73, 40, 0, 0, 42, 0, 0, 0, 1,
	1, 39, 71, 80, 43, 44, 0, 1, 1, 50,
	51, 0, 52, 53, 45,
}
var yyTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 66, 3, 62, 63, 3,
	36, 75, 60, 56, 73, 57, 71, 61, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 74, 72,
	55, 69, 54, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 49, 3, 3, 3, 3, 3,
	3, 35, 3, 70, 59, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 34, 58, 68, 65,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 37, 38, 39, 40, 41, 42, 43, 44,
	45, 46, 47, 48, 50, 51, 52, 53, 64, 67,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:74
		{
			yyVAL.expr = CompNode(AChain)
			if l, ok := yylex.(*Lexer); ok {
				l.Stmts = yyVAL.expr
			}
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:80
		{
			yyVAL.expr = yyDollar[1].expr.Cappend(yyDollar[2].expr)
			if l, ok := yylex.(*Lexer); ok {
				l.Stmts = yyVAL.expr
			}
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:88
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:91
		{
			if yyDollar[1].expr.isIsolatedCopy() {
				yyDollar[1].expr.Cx(2).C()[0] = zeroNode
			}
			yyVAL.expr = yyDollar[1].expr
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:99
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:100
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:101
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:102
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:105
		{
			yyVAL.expr = ChainNode(yyDollar[1].expr)
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:106
		{
			yyVAL.expr = ChainNode(yyDollar[1].expr)
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:107
		{
			yyVAL.expr = ChainNode(yyDollar[1].expr)
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:108
		{
			yyVAL.expr = ChainNode(yyDollar[1].expr)
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:109
		{
			yyVAL.expr = ChainNode(yyDollar[1].expr)
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:110
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:113
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:114
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:115
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:116
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:119
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:120
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:121
		{
			yyVAL.expr = CompNode("move", yyDollar[1].expr, yyDollar[3].expr).setPos0(yyDollar[1].expr)
			if yyDollar[1].expr.Cn() > 0 && yyDollar[1].expr.Cx(0).A() == ALoad {
				yyVAL.expr = CompNode("store", yyDollar[1].expr.Cx(1), yyDollar[1].expr.Cx(2), yyDollar[3].expr)
			}
			if c := yyDollar[1].expr.A(); c != "" && yyDollar[1].expr.Type() == Natom {
				// For 'a = a +/- n', we will simplify it as 'inc a +/- n'
				if a, b, s := yyDollar[3].expr.isSimpleAddSub(); a == c {
					yyDollar[3].expr.Cx(2).Value = yyDollar[3].expr.Cx(2).N() * s
					yyVAL.expr = CompNode("inc", yyDollar[1].expr, yyDollar[3].expr.Cx(2))
					yyVAL.expr.Cx(1).SetPos(yyDollar[1].expr)
				} else if b == c {
					yyDollar[3].expr.Cx(1).Value = yyDollar[3].expr.Cx(1).N() * s
					yyVAL.expr = CompNode("inc", yyDollar[1].expr, yyDollar[3].expr.Cx(1))
					yyVAL.expr.Cx(1).SetPos(yyDollar[1].expr)
				}
			}
			yyVAL.expr.Cx(0).SetPos(yyDollar[1].expr)
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:142
		{
			yyVAL.expr = oneNode
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:143
		{
			yyVAL.expr = moneNode
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:146
		{
			yyVAL.atom = AAdd
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:147
		{
			yyVAL.atom = ASub
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:148
		{
			yyVAL.atom = AMul
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:149
		{
			yyVAL.atom = "/"
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:150
		{
			yyVAL.atom = "%"
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:151
		{
			yyVAL.atom = "&"
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:152
		{
			yyVAL.atom = "|"
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:153
		{
			yyVAL.atom = "^"
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:154
		{
			yyVAL.atom = "<<"
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:155
		{
			yyVAL.atom = ">>"
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:156
		{
			yyVAL.atom = ">>>"
		}
	case 35:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:159
		{
			yyVAL.expr = CompNode("inc", ANode(yyDollar[1].token).setPos(yyDollar[1].token), yyDollar[2].expr)
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:160
		{
			yyVAL.expr = CompNode("move", ANode(yyDollar[1].token), CompNode(yyDollar[2].atom, ANode(yyDollar[1].token).setPos(yyDollar[1].token), yyDollar[3].expr)).setPos0(yyDollar[1].token)
		}
	case 37:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:161
		{
			yyVAL.expr = CompNode("store", yyDollar[1].expr, yyDollar[3].expr, CompNode(AAdd, CompNode(ALoad, yyDollar[1].expr, yyDollar[3].expr).setPos0(yyDollar[1].expr), yyDollar[5].expr).setPos0(yyDollar[1].expr))
		}
	case 38:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:162
		{
			yyVAL.expr = CompNode("store", yyDollar[1].expr, yyDollar[3].token, CompNode(AAdd, CompNode(ALoad, yyDollar[1].expr, yyDollar[3].token).setPos0(yyDollar[1].expr), yyDollar[4].expr).setPos0(yyDollar[1].expr))
		}
	case 39:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:163
		{
			yyVAL.expr = CompNode("store", yyDollar[1].expr, yyDollar[3].expr, CompNode(yyDollar[5].atom, CompNode(ALoad, yyDollar[1].expr, yyDollar[3].expr).setPos0(yyDollar[1].expr), yyDollar[6].expr).setPos0(yyDollar[1].expr))
		}
	case 40:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:166
		{
			yyVAL.expr = CompNode("store", yyDollar[1].expr, yyDollar[3].token, CompNode(yyDollar[4].atom, CompNode(ALoad, yyDollar[1].expr, yyDollar[3].token).setPos0(yyDollar[1].expr), yyDollar[5].expr).setPos0(yyDollar[1].expr))
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:171
		{
			yyVAL.expr = CompNode("for", yyDollar[2].expr, emptyNode, yyDollar[3].expr).setPos0(yyDollar[1].token)
		}
	case 42:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:174
		{
			yyVAL.expr = CompNode("for", yyDollar[3].expr, yyDollar[5].expr, yyDollar[6].expr).setPos0(yyDollar[1].token)
		}
	case 43:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:177
		{
			yyVAL.expr = ChainNode(
				yyDollar[2].expr,
				CompNode("for", yyDollar[4].expr, yyDollar[6].expr, yyDollar[7].expr).setPos0(yyDollar[1].token),
			)
		}
	case 44:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:183
		{
			vname, ename := ANode(yyDollar[2].token), ANodeS(yyDollar[2].token.Str+"_end")
			yyVAL.expr = ChainNode(
				CompNode("move", vname, yyDollar[4].expr).setPos0(yyDollar[1].token),
				CompNode("move", ename, yyDollar[6].expr).setPos0(yyDollar[1].token),
				CompNode("for",
					CompNode(ALess, vname, ename).setPos0(yyDollar[1].token),
					ChainNode(
						CompNode("inc", vname, oneNode).setPos0(yyDollar[1].token),
					),
					yyDollar[7].expr,
				).setPos0(yyDollar[1].token),
			)
		}
	case 45:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser.go.y:197
		{
			vname, sname, ename := ANode(yyDollar[2].token), ANodeS(yyDollar[2].token.Str+"_step"), ANodeS(yyDollar[2].token.Str+"_end")
			if yyDollar[6].expr.Type() == Nnumber {
				// easy case
				chain := ChainNode(CompNode("inc", vname, yyDollar[6].expr).setPos0(yyDollar[1].token))
				var cond *Node
				if yyDollar[6].expr.N() < 0 {
					cond = CompNode("<=", ename, vname)
				} else {
					cond = CompNode("<=", vname, ename)
				}
				yyVAL.expr = ChainNode(
					CompNode("move", vname, yyDollar[4].expr).setPos0(yyDollar[1].token),
					CompNode("move", ename, yyDollar[8].expr).setPos0(yyDollar[1].token),
					CompNode("for", cond, chain, yyDollar[9].expr).setPos0(yyDollar[1].token),
				)
			} else {
				bname := ANodeS(yyDollar[2].token.Str + "_begin")
				yyVAL.expr = ChainNode(
					CompNode("move", vname, yyDollar[4].expr).setPos0(yyDollar[1].token),
					CompNode("move", bname, yyDollar[4].expr).setPos0(yyDollar[1].token),
					CompNode("move", sname, yyDollar[6].expr).setPos0(yyDollar[1].token),
					CompNode("move", ename, yyDollar[8].expr).setPos0(yyDollar[1].token),
					CompNode("if",
						CompNode("<=",
							zeroNode,
							CompNode(AMul,
								CompNode(ASub, ename, vname).setPos0(yyDollar[1].token),
								sname,
							).setPos0(yyDollar[1].token),
						).setPos0(yyDollar[1].token),
						ChainNode(
							CompNode("for",
								CompNode("<=",
									CompNode(AMul,
										CompNode(ASub, vname, bname).setPos0(yyDollar[1].token),
										CompNode(ASub, vname, ename).setPos0(yyDollar[1].token),
									),
									zeroNode,
								).setPos0(yyDollar[1].token),
								ChainNode(
									CompNode("move", vname, CompNode(AAdd, vname, sname).setPos0(yyDollar[1].token)).setPos0(yyDollar[1].token)),
								yyDollar[9].expr,
							).setPos0(yyDollar[1].token),
						),
						CompNode(AChain),
					).setPos0(yyDollar[1].token),
				)
			}

		}
	case 46:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:249
		{
			yyVAL.expr = CompNode("foreach", yyDollar[2].expr, yyDollar[4].expr).setPos0(yyDollar[1].token)
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:254
		{
			yyVAL.expr = CompNode("if", yyDollar[2].expr, yyDollar[3].expr, emptyNode).setPos0(yyDollar[1].token)
		}
	case 48:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:255
		{
			yyVAL.expr = CompNode("if", yyDollar[2].expr, yyDollar[3].expr, yyDollar[5].expr).setPos0(yyDollar[1].token)
		}
	case 49:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:258
		{
			yyVAL.expr = expandSwitch(yyDollar[1].token, yyDollar[2].expr, yyDollar[4].expr.C())
		}
	case 50:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:261
		{
			yyVAL.expr = CompNode(yyDollar[2].expr, yyDollar[4].expr).setPos0(yyDollar[1].token)
		}
	case 51:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:262
		{
			yyVAL.expr = CompNode(ANode(yyDollar[2].token), yyDollar[4].expr).setPos0(yyDollar[1].token)
		}
	case 52:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:263
		{
			yyVAL.expr = yyDollar[1].expr.Cappend(yyDollar[3].expr, yyDollar[5].expr)
		}
	case 53:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:264
		{
			yyVAL.expr = yyDollar[1].expr.Cappend(ANode(yyDollar[3].token), yyDollar[5].expr)
		}
	case 54:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:267
		{
			yyVAL.atom = Atom("")
		}
	case 55:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:268
		{
			yyVAL.atom = yyDollar[1].atom + ",safe"
		}
	case 56:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:269
		{
			yyVAL.atom = yyDollar[1].atom + ",var"
		}
	case 57:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:272
		{
			yyVAL.expr = ANodeS("func," + string(yyDollar[2].atom)).setPos(yyDollar[1].token)
		}
	case 58:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:275
		{
			funcname := ANode(yyDollar[2].token)
			yyVAL.expr = CompNode(
				AChain,
				CompNode("set", funcname, nilNode).setPos0(yyDollar[2].token),
				CompNode("move", funcname,
					CompNode(yyDollar[1].expr, funcname, yyDollar[3].expr, yyDollar[4].expr).setPos0(yyDollar[2].token),
				).setPos0(yyDollar[2].token),
			)
		}
	case 59:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:287
		{
			yyVAL.expr = CompNode("yield", yyDollar[2].expr).setPos0(yyDollar[1].token)
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:288
		{
			yyVAL.expr = CompNode("yield", CompNode("#", nilNode).setPos0(yyDollar[1].token)).setPos0(yyDollar[1].token)
		}
	case 61:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:289
		{
			yyVAL.expr = CompNode("break").setPos0(yyDollar[1].token)
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:290
		{
			yyVAL.expr = CompNode("continue").setPos0(yyDollar[1].token)
		}
	case 63:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:291
		{
			yyVAL.expr = CompNode("assert", yyDollar[2].expr, nilNode).setPos0(yyDollar[1].token)
		}
	case 64:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:292
		{
			yyVAL.expr = CompNode("assert", yyDollar[2].expr, NewNode(yyDollar[3].token.Str)).setPos0(yyDollar[1].token)
		}
	case 65:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:293
		{
			yyVAL.expr = CompNode("ret", yyDollar[2].expr).setPos0(yyDollar[1].token)
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:294
		{
			yyVAL.expr = CompNode("ret", CompNode("#", nilNode).setPos0(yyDollar[1].token)).setPos0(yyDollar[1].token)
		}
	case 67:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:295
		{
			yyVAL.expr = yylex.(*Lexer).loadFile(filepath.Join(filepath.Dir(yyDollar[1].token.Pos.Source), yyDollar[2].token.Str), yyDollar[1].token)
		}
	case 68:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:298
		{
			yyVAL.expr = ANode(yyDollar[1].token).setPos(yyDollar[1].token)
		}
	case 69:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:299
		{
			yyVAL.expr = CompNode(ALoad, nilNode, yyDollar[1].token.Str).setPos0(yyDollar[1].token)
		}
	case 70:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:300
		{
			yyVAL.expr = CompNode(ALoad, yyDollar[1].expr, yyDollar[3].expr).setPos0(yyDollar[3].expr).setPos(yyDollar[3].expr)
		}
	case 71:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:301
		{
			yyVAL.expr = CompNode(ASlice, yyDollar[1].expr, yyDollar[3].expr, yyDollar[5].expr).setPos0(yyDollar[3].expr).setPos(yyDollar[3].expr)
		}
	case 72:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:302
		{
			yyVAL.expr = CompNode(ASlice, yyDollar[1].expr, yyDollar[3].expr, moneNode).setPos0(yyDollar[3].expr).setPos(yyDollar[3].expr)
		}
	case 73:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:303
		{
			yyVAL.expr = CompNode(ASlice, yyDollar[1].expr, zeroNode, yyDollar[4].expr).setPos0(yyDollar[4].expr).setPos(yyDollar[4].expr)
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:304
		{
			yyVAL.expr = CompNode(ALoad, yyDollar[1].expr, NewNode(yyDollar[3].token.Str)).setPos0(yyDollar[3].token).setPos(yyDollar[3].token)
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:307
		{
			yyVAL.expr = CompNode(yyDollar[1].token.Str)
		}
	case 76:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:308
		{
			yyVAL.expr = yyDollar[1].expr.Cappend(ANode(yyDollar[3].token))
		}
	case 77:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:311
		{
			yyVAL.expr = CompNode(yyDollar[1].expr)
		}
	case 78:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:312
		{
			yyVAL.expr = yyDollar[1].expr.Cappend(yyDollar[3].expr)
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:315
		{
			yyVAL.expr = CompNode(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 80:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:316
		{
			yyVAL.expr = yyDollar[1].expr.Cappend(yyDollar[3].expr).Cappend(yyDollar[5].expr)
		}
	case 81:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:319
		{
			yyVAL.expr = NewNumberNode(yyDollar[1].token.Str).SetPos(yyDollar[1].token)
		}
	case 82:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:320
		{
			yyVAL.expr = yylex.(*Lexer).loadFile(filepath.Join(filepath.Dir(yyDollar[1].token.Pos.Source), yyDollar[2].token.Str), yyDollar[1].token)
		}
	case 83:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:321
		{
			yyVAL.expr = CompNode("typeof", yyDollar[2].expr)
		}
	case 84:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:322
		{
			yyVAL.expr = CompNode("len", yyDollar[2].expr)
		}
	case 85:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:323
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 86:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:324
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 87:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:325
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 88:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:326
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 89:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:327
		{
			yyVAL.expr = NewNode(yyDollar[1].token.Str).SetPos(yyDollar[1].token)
		}
	case 90:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:328
		{
			yyVAL.expr = CompNode("or", yyDollar[1].expr, yyDollar[3].expr).setPos0(yyDollar[1].expr)
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:329
		{
			yyVAL.expr = CompNode("and", yyDollar[1].expr, yyDollar[3].expr).setPos0(yyDollar[1].expr)
		}
	case 92:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:330
		{
			yyVAL.expr = CompNode(ALess, yyDollar[3].expr, yyDollar[1].expr).setPos0(yyDollar[1].expr)
		}
	case 93:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:331
		{
			yyVAL.expr = CompNode(ALess, yyDollar[1].expr, yyDollar[3].expr).setPos0(yyDollar[1].expr)
		}
	case 94:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:332
		{
			yyVAL.expr = CompNode("<=", yyDollar[3].expr, yyDollar[1].expr).setPos0(yyDollar[1].expr)
		}
	case 95:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:333
		{
			yyVAL.expr = CompNode("<=", yyDollar[1].expr, yyDollar[3].expr).setPos0(yyDollar[1].expr)
		}
	case 96:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:334
		{
			yyVAL.expr = CompNode("==", yyDollar[1].expr, yyDollar[3].expr).setPos0(yyDollar[1].expr)
		}
	case 97:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:335
		{
			yyVAL.expr = CompNode("!=", yyDollar[1].expr, yyDollar[3].expr).setPos0(yyDollar[1].expr)
		}
	case 98:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:336
		{
			yyVAL.expr = CompNode(AAdd, yyDollar[1].expr, yyDollar[3].expr).setPos0(yyDollar[1].expr)
		}
	case 99:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:337
		{
			yyVAL.expr = CompNode(ASub, yyDollar[1].expr, yyDollar[3].expr).setPos0(yyDollar[1].expr)
		}
	case 100:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:338
		{
			yyVAL.expr = CompNode(AMul, yyDollar[1].expr, yyDollar[3].expr).setPos0(yyDollar[1].expr)
		}
	case 101:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:339
		{
			yyVAL.expr = CompNode("/", yyDollar[1].expr, yyDollar[3].expr).setPos0(yyDollar[1].expr)
		}
	case 102:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:340
		{
			yyVAL.expr = CompNode("%", yyDollar[1].expr, yyDollar[3].expr).setPos0(yyDollar[1].expr)
		}
	case 103:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:341
		{
			yyVAL.expr = CompNode("^", yyDollar[1].expr, yyDollar[3].expr).setPos0(yyDollar[1].expr)
		}
	case 104:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:342
		{
			yyVAL.expr = CompNode("<<", yyDollar[1].expr, yyDollar[3].expr).setPos0(yyDollar[1].expr)
		}
	case 105:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:343
		{
			yyVAL.expr = CompNode(">>", yyDollar[1].expr, yyDollar[3].expr).setPos0(yyDollar[1].expr)
		}
	case 106:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:344
		{
			yyVAL.expr = CompNode(">>>", yyDollar[1].expr, yyDollar[3].expr).setPos0(yyDollar[1].expr)
		}
	case 107:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:345
		{
			yyVAL.expr = CompNode("|", yyDollar[1].expr, yyDollar[3].expr).setPos0(yyDollar[1].expr)
		}
	case 108:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:346
		{
			yyVAL.expr = CompNode("&", yyDollar[1].expr, yyDollar[3].expr).setPos0(yyDollar[1].expr)
		}
	case 109:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:347
		{
			yyVAL.expr = CompNode(ASub, zeroNode, yyDollar[2].expr).setPos0(yyDollar[2].expr)
		}
	case 110:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:348
		{
			yyVAL.expr = CompNode("^", yyDollar[2].expr, max32Node).setPos0(yyDollar[2].expr)
		}
	case 111:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:349
		{
			yyVAL.expr = CompNode("!", yyDollar[2].expr).setPos0(yyDollar[2].expr)
		}
	case 112:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:350
		{
			yyVAL.expr = CompNode("#", yyDollar[2].expr).setPos0(yyDollar[2].expr)
		}
	case 113:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:351
		{
			yyVAL.expr = CompNode("addressof", ANode(yyDollar[2].token)).setPos0(yyDollar[2].token)
		}
	case 114:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:354
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 115:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:355
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 116:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:356
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 117:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:357
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 118:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:360
		{
			yyVAL.expr = CompNode("call", yyDollar[1].expr, yyDollar[2].expr).setPos0(yyDollar[1].expr)
		}
	case 119:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:363
		{
			yyVAL.expr = emptyNode
		}
	case 120:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:364
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 121:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:367
		{
			yyVAL.expr = CompNode(yyDollar[1].expr, "<a>", yyDollar[2].expr, yyDollar[3].expr).setPos0(yyDollar[1].expr)
		}
	case 122:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:368
		{
			yyVAL.expr = CompNode(yyDollar[1].expr, "<a>", yyDollar[2].expr, ChainNode(CompNode("ret", yyDollar[4].expr).setPos0(yyDollar[1].expr))).setPos0(yyDollar[1].expr)
		}
	case 123:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:369
		{
			yyVAL.expr = CompNode(yyDollar[1].expr, "<a>", emptyNode, ChainNode(CompNode("ret", yyDollar[3].expr).setPos0(yyDollar[1].expr))).setPos0(yyDollar[1].expr)
		}
	case 124:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:372
		{
			yyVAL.expr = emptyNode
		}
	case 125:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:373
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 126:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:376
		{
			yyVAL.expr = CompNode("map", emptyNode).setPos0(yyDollar[1].token)
		}
	case 127:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:377
		{
			yyVAL.expr = yyDollar[2].expr.setPos0(yyDollar[1].token)
		}
	case 128:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:380
		{
			yyVAL.expr = CompNode("map", yyDollar[1].expr).setPos0(yyDollar[1].expr)
		}
	case 129:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:381
		{
			yyVAL.expr = CompNode("map", yyDollar[1].expr).setPos0(yyDollar[1].expr)
		}
	case 130:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:382
		{
			yyVAL.expr = CompNode("array", yyDollar[1].expr).setPos0(yyDollar[1].expr)
		}
	case 131:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:383
		{
			yyVAL.expr = CompNode("array", yyDollar[1].expr).setPos0(yyDollar[1].expr)
		}
	}
	goto yystack /* stack new state and value */
}
